#!/bin/bash
# Show common Yandex regions

printf "=== Common Region IDs ===\n\n"
printf "Countries:\n"
printf "  225 - Россия\n"
printf "  159 - Казахстан\n"
printf "  187 - Украина\n"
printf "  149 - Беларусь\n\n"
printf "Federal Districts (Russia):\n"
printf "  3   - Центральный ФО\n"
printf "  17  - Северо-Западный ФО\n"
printf "  40  - Приволжский ФО\n"
printf "  52  - Уральский ФО\n"
printf "  59  - Сибирский ФО\n"
printf "  73  - Южный ФО\n"
printf "  26  - Дальневосточный ФО\n\n"
printf "Major Cities:\n"
printf "  213 - Москва\n"
printf "  2   - Санкт-Петербург\n"
printf "  54  - Екатеринбург\n"
printf "  65  - Новосибирск\n"
printf "  43  - Казань\n"
printf "  35  - Краснодар\n"
printf "  47  - Нижний Новгород\n"
printf "  39  - Ростов-на-Дону\n"
printf "  51  - Самара\n"
printf "  172 - Уфа\n\n"
printf "Moscow Region:\n"
printf "  1   - Москва и область\n"
printf "  213 - Москва (город)\n"
printf "  10716 - Московская область\n\n"
printf "Use these IDs with --regions parameter in other scripts.\n"
printf "Example: bash scripts/top_requests.sh --phrase \"test\" --regions 213\n"
